### ISSUE TITLE
Day 6 Intuition

### ISSUE THREAD

**Issue by alexkolson** [timvisee/advent-of-code-2021#11]
Hey Tim it's me again 👋 

If you have a moment, would love some explanation behind your day 6 optimized solution, purely out of curiosity. How did you come up with it? Thanks!

Absolutely no worries at all if you do not have time/desire to answer! But thought I'd ask just in case you do.

**Comment by timvisee** [comment]
Hi Alex,

Sure! Please see: https://github.com/timvisee/advent-of-code-2021/issues/3#issuecomment-986883821
