### ISSUE TITLE
Where is hyperfine used?

### ISSUE THREAD

**Issue by GaurangTandon** [timvisee/advent-of-code-2021#2]
Hello, thanks for putting these solutions! 

I wish to ask where `hyperfine` is used in the codebase, as it is mentioned in the README. It seems to me that the `runner` rust programs are using the `took` crate instead.

**Comment by timvisee** [comment]
Good question. I originally used `hyperfine` to measure each binary manually, especially the previous years.

Now I just shifted to using the runtime from `took` as outputted by the `runner`.

I should probably remove the `hyperfine` note.

**Comment by GaurangTandon** [comment]
Cool, thanks for letting me know.
