### ISSUE TITLE
Solution for day 7, part B is incorrect

### ISSUE THREAD

**Issue by smarnach** [timvisee/advent-of-code-2021#4]
For the input

    1,1,1,1,1,1,20

the current code returns 172, while the correct minimal fuel consumption is 171. After doing a few estimates with paper and pencil, I believe it's enough to check the ceiled and floored arithmetic mean, but simply rounding to the nearest integer is not enough.

Note that the current code also fails on real-world Advent of Code inputs, notably on mine. :)

A solution I believe to be correct is here: https://github.com/smarnach/aoc2021/blob/master/src/bin/day07.rs

**Comment by timvisee** [comment]
Woah, thanks for this! I actually checked both before, and [then](https://github.com/timvisee/advent-of-code-2021/commit/0c397f8f2cd4ebdcbc1ed6e204aa1b6caff845eb) badly assumed rounding the mean would be good enough as it worked in my case.

I've [reverted](https://github.com/timvisee/advent-of-code-2021/commit/de0ec8bebc12db0f96023f7b7545749fb2270420) this to check both again, fixing the issue.

Thanks again.
